name=input("Enter your name: ")
age=input("Enter your age: ")
city=input("Enter your city: ")
state=input("Enter your state: ")
country=input("Enter your county: ")
print("Name:",name)
print("Age:",age)
print("City:",city)
print("State:",state)
print("Country:",country)
