'''Take a string as input.The input string consists of numbers also.
Generate a new string from the input string in such a way that the numbers
in the string should be replaced by a character which is generated by considering the
previous character in following manner:
The new character is generated by adding the ascii value of previous character
with the number and getting the character for the present location.
Example:If the previous character is a and the number is 9 then take the 9th
character after a which is j and replace the number by j.
'''

s=input()
res=""
for i in s:
    if i.isalpha():
        res+=i
        x=i
    else:
        d=chr((ord(x)-ord('a')+ord(i)-ord('0'))%26+97) 
        res+=d
print(res)
