sub1=float(input("Enter the marks of 1st subject:"))
sub2=float(input("Enter the marks of 2nd subject:"))
sub3=float(input("Enter the marks of 3rd subject:"))
sub4=float(input("Enter the marks of 4th subject:"))
sub5=float(input("Enter the marks of 5th subject:"))
total=float(sub1+sub2+sub3+sub4+sub5)
avg=float(total/5)
print("Total marks obtained:",total)
print("Average is:",avg)
